### ISSUE TITLE
"Reaching a directly connected gateway" examples are wrong

### ISSUE THREAD

**Issue by basak** [canonical-web-and-design/netplan.io#153]
I believe these examples are wrong. `addresses` and `routes` are being specified directly under `ethernets` instead of under an example interface name under `ethernets`.

**Comment by basak** [comment]
For reference this is what there is right now:

```
network:
    version: 2
    renderer: networkd
    ethernets:
        addresses: [ "10.10.10.1/24" ]
        routes:
            - to: 0.0.0.0/0
                via: 9.9.9.9
                on-link: true
```

(and similar for the following IPv6 example)
