### ISSUE TITLE
bonding example is wrong

### ISSUE THREAD

**Issue by axinojolais** [canonical-web-and-design/netplan.io#84]
## Summary

The first bonding example is wrong

## Process

Using this file :

```
  bonds:
    bond0:
      dhcp4: no
      interfaces:
        - eth1
      parameters:
        mode: 802.3ad
        miimon: 100
        xmit-hash-policy: layer3+4
```

## Current and expected result

I expected the bond to be created, but
```
$ sudo netplan generate
/etc/netplan/01-netcfg.yaml:18:11: Error in network definition: bond0: interface 'eth1' is not defined
        - eth1
          ^

```

**Comment by anthonydillon** [comment]
@cyphermox @powersj Could you take a look at this and advise the change required.

**Comment by powersj** [comment]
Right, the example is only showing the `bonds` section of the YAML. You will also still need to define the interface under `ethernets`. For example:

```
  ethernets:
    ens4:
      dhcp4: no
```

A fully complete example, but one that still needs an IP address assigned to the bond, would look like:

```
network:
  version: 2
  renderer: networkd
  ethernets:
    ens4:
      dhcp4: no
  bonds:
    bond0:
      dhcp4: no
      interfaces:
        - ens4
      parameters:
        mode: 802.3ad
        mii-monitor-interval: 100
        transmit-hash-policy: layer3+4
```
