### ISSUE TITLE
Override default gateway when using netplan DHCP doesn't work

### ISSUE THREAD

**Issue by icalvete** [canonical-web-and-design/netplan.io#87]
## Summary

I'm trying override default gateway when using netplan DHCP without sucess

## Process

Into a ubuntu 18.04.03 instance running within AWS EC2 I have this config... (netplan.io version 0.98-0ubuntu1~18.04.1)

```
network:
    version: 2
    ethernets:
        ens5:
            dhcp4: true
            dhcp4-overrides:
                use-routes: false
            routes:
                - to: 0.0.0.0/0
                  via: 11.0.0.254
                  metric: 0
            match:
                macaddress: 06:c1:fa:00:3d:16
            set-name: ens5
```

## Current and expected result

After runing netplan apply I expected all routes wil be deleted and a new gateway will be added. 
Instead, all routes are deleted but no gateway are added.
